USE OLISTENTERPRISEDB;
GO

-- ADD A COLUMN TO SILVER.ORDERS
ALTER TABLE SILVER.ORDERS 
ADD ESTIMATEDDELIVERYDATE DATETIME2;
GO

-- BACKFILL THE COLUMN FROM BRONZE.ORDERS
UPDATE SILVER.ORDERS
SET ESTIMATEDDELIVERYDATE = TRY_CAST(B.ORDER_ESTIMATED_DELIVERY_DATE AS DATETIME2)
FROM SILVER.ORDERS S
JOIN BRONZE.ORDERS B ON S.ORDERID = B.ORDER_ID;
GO