CREATE OR ALTER VIEW GOLD.VW_CUSTOMERANALYTICS AS
WITH ORDERSTATS AS (
SELECT O.ORDERID,
       C.CUSTOMERUNIQUEID,
       O.PURCHASEDATE,
       LAG(O.PURCHASEDATE) OVER (PARTITION BY C.CUSTOMERUNIQUEID ORDER BY O.PURCHASEDATE) AS PREV_ORDER_DATE
FROM SILVER.ORDERS O
JOIN SILVER.CUSTOMERS C 
ON O.CUSTOMERID = C.CUSTOMERID)

SELECT S.CUSTOMERUNIQUEID,
       COUNT(DISTINCT S.ORDERID) AS LIFETIMEORDERS,
       SUM(I.PRICE) AS TOTALSPEND,
       AVG(CAST(DATEDIFF(DAY, S.PREV_ORDER_DATE, S.PURCHASEDATE) AS FLOAT)) AS AVGDAYSBETWEENORDERS
FROM ORDERSTATS S
JOIN SILVER.ORDERITEMS I 
ON S.ORDERID = I.ORDERID
GROUP BY S.CUSTOMERUNIQUEID;