-- TEST 1: CHECK FOR ORPHANED ORDER ITEMS (ITEMS THAT DON'T BELONG TO A VALID ORDER)
-- IF THIS RETURNS > 0, WE HAVE A DATA INTEGRITY ISSUE FROM THE SOURCE.
SELECT COUNT(*) AS ORPHANEDITEMS
FROM BRONZE.ORDERITEMS I
LEFT JOIN BRONZE.ORDERS O 
ON I.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;

-- TEST 2: IDENTIFY FREIGHT OUTLIERS USING STATISTICAL Z-SCORE
-- FLAGS ROWS WHERE THE SHIPPING COST IS 3 STANDARD DEVIATIONS ABOVE THE AVERAGE.
WITH FREIGHTSTATS AS (
SELECT PRODUCT_ID, 
        CAST(FREIGHT_VALUE AS FLOAT) AS FREIGHT_COST,
        AVG(CAST(FREIGHT_VALUE AS FLOAT)) OVER() AS AVG_FREIGHT,
        STDEV(CAST(FREIGHT_VALUE AS FLOAT)) OVER() AS STD_FREIGHT
FROM BRONZE.ORDERITEMS
WHERE TRY_CAST(FREIGHT_VALUE AS FLOAT) IS NOT NULL)

SELECT PRODUCT_ID, 
	   ROUND(FREIGHT_COST, 2)
FROM FREIGHTSTATS
WHERE FREIGHT_COST > (AVG_FREIGHT + (3 * STD_FREIGHT));