USE OLISTENTERPRISEDB;
GO

-- ALTER THE TARGET COLUMNS TO REJECT NULL VALUES
ALTER TABLE SILVER.CUSTOMERS ALTER COLUMN CUSTOMERID VARCHAR(100) NOT NULL;
ALTER TABLE SILVER.PRODUCTS ALTER COLUMN PRODUCTID VARCHAR(100) NOT NULL;
ALTER TABLE SILVER.ORDERS ALTER COLUMN ORDERID VARCHAR(100) NOT NULL;

-- ORDERITEMS NEEDS BOTH COLUMNS SET TO NOT NULL FOR ITS COMPOSITE KEY
ALTER TABLE SILVER.ORDERITEMS ALTER COLUMN ORDERID VARCHAR(100) NOT NULL;
ALTER TABLE SILVER.ORDERITEMS ALTER COLUMN ORDERITEMID INT NOT NULL;
GO

-- ADD PRIMARY KEYS
ALTER TABLE SILVER.CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMERID);
ALTER TABLE SILVER.PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID);
ALTER TABLE SILVER.ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ORDERID);
ALTER TABLE SILVER.ORDERITEMS ADD CONSTRAINT PK_ORDERITEMS PRIMARY KEY (ORDERID, ORDERITEMID);
GO

-- ADD FOREIGN KEYS
ALTER TABLE SILVER.ORDERS 
ADD CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMERID) REFERENCES SILVER.CUSTOMERS(CUSTOMERID);

ALTER TABLE SILVER.ORDERITEMS 
ADD CONSTRAINT FK_ITEMS_ORDERS FOREIGN KEY (ORDERID) REFERENCES SILVER.ORDERS(ORDERID);

ALTER TABLE SILVER.ORDERITEMS 
ADD CONSTRAINT FK_ITEMS_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES SILVER.PRODUCTS(PRODUCTID);
GO;