USE OLISTENTERPRISEDB;
GO

-- SILVER CUSTOMERS
SELECT 
    CAST(CUSTOMER_ID AS VARCHAR(100)) AS CUSTOMERID,
    CAST(CUSTOMER_UNIQUE_ID AS VARCHAR(100)) AS CUSTOMERUNIQUEID,
    UPPER(CUSTOMER_CITY) AS CITY,
    UPPER(CUSTOMER_STATE) AS STATE
INTO SILVER.Customers
FROM BRONZE.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

-- SILVER PRODUCTS
SELECT 
    CAST(PRODUCT_ID AS VARCHAR(100)) AS PRODUCTID,
    ISNULL(PRODUCT_CATEGORY_NAME, 'unknown_category') AS CATEGORY,
    TRY_CAST(PRODUCT_WEIGHT_G AS INT) AS WEIGHTGRAMS
INTO SILVER.Products
FROM BRONZE.PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

-- SILVER ORDERS
SELECT 
    CAST(ORDER_ID AS VARCHAR(100)) AS ORDERID,
    CAST(CUSTOMER_ID AS VARCHAR(100)) AS CUSTOMERID,
    LOWER(ORDER_STATUS) AS ORDERSTATUS,
    TRY_CAST(ORDER_PURCHASE_TIMESTAMP AS DATETIME2) AS PURCHASEDATE,
    TRY_CAST(ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME2) AS DELIVERYDATE
INTO SILVER.Orders
FROM BRONZE.ORDERS
WHERE ORDER_ID IS NOT NULL;

-- SILVER ORDER ITEMS
SELECT 
    CAST(ORDER_ID AS VARCHAR(100)) AS ORDERID,
    TRY_CAST(ORDER_ITEM_ID AS INT) AS ORDERITEMID,
    CAST(PRODUCT_ID AS VARCHAR(100)) AS PRODUCTID,
    TRY_CAST(PRICE AS DECIMAL(10,2)) AS PRICE,
    TRY_CAST(FREIGHT_VALUE AS DECIMAL(10,2)) AS FREIGHTVALUE
INTO SILVER.OrderItems
FROM BRONZE.ORDERITEMS
WHERE ORDER_ID IS NOT NULL;